using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AlicizaX.Event.SourceGenerators
{
    [Generator]
    public class EventGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            // 不使用语法接收器，直接在 Execute 中遍历 Compilation
        }

        public void Execute(GeneratorExecutionContext context)
        {
            var compilation = context.Compilation;


            var iEventArgsSymbol1 = compilation.GetTypeByMetadataName("AlicizaX.IEventArgs");


            var prewarmSymbol = compilation.GetTypeByMetadataName("AlicizaX.PrewarmAttribute");

            if (prewarmSymbol == null)
            {
                // 如果找不到 PrewarmAttribute，就无需生成
                return;
            }

            var collected = new List<(INamedTypeSymbol symbol, int capacity)>();

            // 遍历所有语ntax trees，找类型声明并通过语义模型确认
            foreach (var tree in compilation.SyntaxTrees)
            {
                var semanticModel = compilation.GetSemanticModel(tree);
                var root = tree.GetRoot();

                // 找到所有 type declarations (class/struct)
                var typeDecls = root.DescendantNodes().OfType<TypeDeclarationSyntax>();

                foreach (var td in typeDecls)
                {
                    var sym = semanticModel.GetDeclaredSymbol(td) as INamedTypeSymbol;
                    if (sym == null) continue;

                    // 必须是 struct 类型
                    if (sym.TypeKind != TypeKind.Struct) continue;

                    // 必须实现 IEventArgs （支持多个符号）
                    bool implementsIEventArgs = false;
                    if (iEventArgsSymbol1 != null && sym.AllInterfaces.Contains(iEventArgsSymbol1, SymbolEqualityComparer.Default))
                        implementsIEventArgs = true;
                    if (!implementsIEventArgs) continue;

                    // 检查是否有 PrewarmAttribute，并读取构造参数 int
                    foreach (var attr in sym.GetAttributes())
                    {
                        if (!SymbolEqualityComparer.Default.Equals(attr.AttributeClass, prewarmSymbol))
                            continue;

                        // 期望 attribute constructor: PrewarmAttribute(int capacity)
                        if (attr.ConstructorArguments.Length == 1 && attr.ConstructorArguments[0].Value is int capacity)
                        {
                            collected.Add((sym, capacity));
                        }
                    }
                }
            }

            if (collected.Count == 0)
                return;

            // 生成代码
            var source = GenerateSource(collected);
            context.AddSource("EventPrewarmRegister.g.cs", SourceText.From(source, Encoding.UTF8));
        }

        private string GenerateSource(List<(INamedTypeSymbol symbol, int capacity)> items)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using AlicizaX;");
            sb.AppendLine();

            sb.AppendLine("public static class EventPrewarmRegister");
            sb.AppendLine("{");
            sb.AppendLine("#if UNITY_EDITOR");
            sb.AppendLine("    [UnityEditor.InitializeOnEnterPlayMode]");
            sb.AppendLine("#else");
            sb.AppendLine("    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]");
            sb.AppendLine("#endif");
            sb.AppendLine("    public static void Prewarm()");
            sb.AppendLine("    {");

            // 按字母序生成，便于比较 diff
            foreach (var (sym, cap) in items.OrderBy(t => t.symbol.ToDisplayString()))
            {
                // 使用 FullyQualifiedFormat 以防命名冲突（会产生 global:: 前缀）
                var fq = sym.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"        EventInitialSize<{fq}>.Size = {cap};");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
